const TASK_STATES = require("./taskStates");

const TASK_TRANSITIONS = Object.freeze({

  [TASK_STATES.DRAFT]: [
    TASK_STATES.OPEN
  ],

  [TASK_STATES.OPEN]: [
    TASK_STATES.ASSIGNED,
    TASK_STATES.CANCELLED
  ],

  [TASK_STATES.ASSIGNED]: [
    TASK_STATES.IN_PROGRESS,
    TASK_STATES.CANCELLED
  ],

  [TASK_STATES.IN_PROGRESS]: [
    TASK_STATES.SUBMITTED,
    TASK_STATES.CANCELLED
  ],

  [TASK_STATES.SUBMITTED]: [
    TASK_STATES.APPROVED,
    TASK_STATES.REVISION_REQUESTED,
    TASK_STATES.DISPUTED
  ],

  [TASK_STATES.REVISION_REQUESTED]: [
    TASK_STATES.IN_PROGRESS
  ],

  [TASK_STATES.APPROVED]: [
    TASK_STATES.COMPLETED
  ],

  [TASK_STATES.DISPUTED]: [
    TASK_STATES.APPROVED,
    TASK_STATES.CANCELLED
  ]

});

module.exports = TASK_TRANSITIONS;